### PR TITLE
MP1.6 non-php7 - fixed UniqueId() and crashes Player joins full Server

### PR DESCRIPTION
**Pull request by ecoron**
just small changes solving Crashes with UniqueId and Crashes if player enters a full server.
there might be some more changes needed in the DataProvider classes. replace IP with uuid.
also switcht the versions in plugin.yml
added a phar 1.8.1 with this fixes

### CODE REVIEW

**Comment by PEMapModder** [comment]
The API version is PHP 7 now.
And please rebase your commits

**Comment by ecoron** [comment]
ok i will do that as soon as possible.
but not shure what you mean with "The API version is PHP 7 now."?
in my opinion is 0.13.1 the version for 1.6 non-php7  and 2.0.0 for php7

**Comment by PEMapModder** [comment]
Sorry I meant 2.0.0

**Comment by ecoron** [comment]
its rebased now to one commit.
but how goes it's forward? SimpleAuth isn't on API 2.0.0 yet,
i think its a good idea to bring up a version that solves the issues on 1.6_dev servers with 01.13.1 api
and going forward porting this plugin to API 2.0.0 php7

**Comment by PEMapModder** [comment]
1.13.0 API allows 1.12.0 plugins to be loaded.

**Comment by ecoron** [comment]
but on the other hand the changes in 0.13 can cause crashes in 0.12 servers, since there are not full compatibel

**Comment by PEMapModder** [comment]
BTW, I don't think you should put your name in the authors :P

**Comment by shoghicp** [comment]
This is not the way to do it and 1.6 is not supported, master is not even a good idea for a PR

**Pull request closed without merging**
